task02
AliaksandrShchuchenka/exadel-python-course-2021 pull request #2
Opened 2021-09-17 09:08 UTC by AliaksandrShchuchenka

2021-09-21 10:21 UTC, 0leksiiLeshchenko requested changes

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +# Function to check if number is narcissistic
```suggestion
```

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +def printmenu():
```suggestion
def print_menu():
```

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +def calch():
Я бы переназвал для понятности. Например `calc_by_base` или `calc_by_height`. Нам же не жалко букаф

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +def calca():
По аналогии с calch

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +    areaFloat = 0.5*base*height
```suggestion
    areaFloat = 0.5 * base * height
```

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +    import math
Импортируем всегда в начале файла. Есть исключения, но это явно не оно. Помести на строку 1 и затем нужно дать 2 пробелла перед объявлением функции

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +    areafloat = float(0.5*sideA*sideB*sin)
```suggestion
    area_float = float(0.5 * sideA * sideB * sin)
```

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +    angle = int(parts[2])
тут очень удачно подходит тот способ что показывал Семен: распаковка + map
```suggestion
    sideA, sideB, angle = map(int, parts)
```

2021-09-21 10:21 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +print("Goodbye!")
```suggestion
print("Goodbye!")

```

2021-09-21 20:18 UTC, AliaksandrShchuchenka commented
Hi Alex. Could you please review my refactoring (in accordance with your comments)?

2021-09-22 08:49 UTC, 0leksiiLeshchenko requested changes

2021-09-22 08:49 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +while i != 3:
Тут лучше сделать бесконечный цикл и проверять на равенство 1 2 или 3. Если введено что-то другое - продолжаем крутиться в цикле

2021-09-22 08:49 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +# Method calculation of triangle area by provided base and height
Комментарии можно удалить

2021-09-22 08:49 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +    angle = int(parts[2])
```suggestion
    side_a, side_b, angle = map(float, s.split())
```

2021-10-01 08:49 UTC, 0leksiiLeshchenko approved these changes

2021-10-01 08:49 UTC, 0leksiiLeshchenko commented on tasks/task02/TriangleArea.py
> +        exit()
```suggestion
        break
```

2021-10-14 19:22 UTC, merged