task03
AliaksandrShchuchenka/exadel-python-course-2021 pull request #3
Opened 2021-09-18 20:06 UTC by AliaksandrShchuchenka

2021-09-21 10:44 UTC, 0leksiiLeshchenko requested changes

2021-09-21 10:44 UTC, 0leksiiLeshchenko commented on tasks/task03/task03.py
> +# Settings for print
Используй [f-string alignment](https://www.geeksforgeeks.org/string-alignment-in-python-f-string/) для форматирования вывода

2021-09-21 10:44 UTC, 0leksiiLeshchenko commented on tasks/task03/task03.py
> +            d[wl] = (r, 1)
Пожалуйста, перепиши используя нормальные названия переменных, что бы они отображали содержание переменных. Буков не жалей)
res -> result
w -> ?
wl -> ?
drn -> ?
...

2021-09-21 10:44 UTC, 0leksiiLeshchenko commented on tasks/task03/task03.py
> +            d[wl] = (r, 1)
по всему файлу, пожалуйста

2021-09-21 20:44 UTC, AliaksandrShchuchenka commented on tasks/task03/task03.py
> +            d[wl] = (r, 1)
Done

2021-09-21 20:45 UTC, AliaksandrShchuchenka commented
I've fixed all comments. Please review.

2021-09-23 12:13 UTC, 0leksiiLeshchenko approved these changes
Так все хорошо :)

2021-09-29 06:53 UTC, merged